{
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 3,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "A7BHcJ-1HDn3",
        "outputId": "0159b8e2-a4ac-4b80-f228-5ca32439f258"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Mounted at /content/gdrive\n"
          ]
        }
      ],
      "source": [
        "from google.colab import drive\n",
        "drive.mount('/content/gdrive')"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 4,
      "metadata": {
        "id": "Fg7erQ71UgEa"
      },
      "outputs": [],
      "source": [
        "import random"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 29,
      "metadata": {
        "id": "KufRQeibJfra"
      },
      "outputs": [],
      "source": [
        "def choose_word(fname: str) -> str:\n",
        "    \"\"\"\n",
        "    Chooses a random word from a text file containing a list of words.\n",
        "\n",
        "    Arg(s):\n",
        "        fname (str):            The path to the file containing a list of possible words.\n",
        "                                Each word should be on a separate line.\n",
        "\n",
        "    Returns:\n",
        "              (str):            A randomly selected word from the file.\n",
        "\n",
        "    Example(s):\n",
        "    >>> choose_word('word_bank.txt')\n",
        "        'water'\n",
        "    >>> choose_word('word_bank.txt')\n",
        "        'mountain'\n",
        "    \"\"\"\n",
        "\n",
        "    folder_path = '/content/gdrive/MyDrive/Colab Notebooks/text_files/'\n",
        "    with open(folder_path + fname, 'r') as file:\n",
        "        lines = file.readlines()\n",
        "\n",
        "    word_list = [line.strip() for line in lines]\n",
        "\n",
        "    return random.choice(word_list)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 6,
      "metadata": {
        "id": "x87JSj9vK4DM"
      },
      "outputs": [],
      "source": [
        "def display_word(word, guessed_letters) -> str:\n",
        "    \"\"\"\n",
        "    Constructs and returns a partially revealed version of the word based on the guessed letters.\n",
        "\n",
        "    Args:\n",
        "        word (str):                         The target word that the player is attempting to guess.\n",
        "        guessed_letters (set):              A set of letters that the player has guessed so far.\n",
        "\n",
        "    Returns:\n",
        "        displayed_word (str):               A string where correctly guessed letters appear in their positions,\n",
        "                                            and unguessed letters are represented as underscores. Letters are separated by spaces for readability.\n",
        "\n",
        "    Examples:\n",
        "    >>> If the word is \"water\" and guessed_letters is {'a', 'n'},\n",
        "        the function returns \"_ a n _ _ a n\".\n",
        "    >>> If the word is \"mountain\" and guessed_letters is {'n'},\n",
        "        the function returns \"_ _ _ n _ _ _ n\".\n",
        "    \"\"\"\n",
        "\n",
        "    displayed_word = \"\"\n",
        "    for letter in word:\n",
        "        if letter.lower() in guessed_letters:\n",
        "            displayed_word += letter + \" \"\n",
        "        else:\n",
        "            displayed_word += \"_ \"\n",
        "    return displayed_word.strip()\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 17,
      "metadata": {
        "id": "N9Jht1_o55rE"
      },
      "outputs": [],
      "source": [
        "def display_hangman(attempts) -> str:\n",
        "    \"\"\"\n",
        "    Displays the current state of the hangman figure based on the remaining attempts.\n",
        "\n",
        "    Args:\n",
        "        attempts (int):             The number of remaining incorrect guesses.\n",
        "                                    Must be an integer between 0 and 6, inclusive.\n",
        "\n",
        "    Returns:\n",
        "                 (str):             A string representing the current hangman figure. Each stage corresponds\n",
        "                                    to a specific number of attempts remaining, starting from an empty frame\n",
        "                                    to a fully drawn hangman.\n",
        "\n",
        "    Examples:\n",
        "    >>> display_hangman(0)\n",
        "           -----\n",
        "           |   |\n",
        "               |\n",
        "               |\n",
        "               |\n",
        "               |\n",
        "        =========\n",
        "    >>> display_hangman(6)\n",
        "           -----\n",
        "           |   |\n",
        "           O   |\n",
        "          /|\\  |\n",
        "          / \\  |\n",
        "        =========\n",
        "    \"\"\"\n",
        "\n",
        "    stages = [\n",
        "    '''\n",
        "        -----\n",
        "        |   |\n",
        "            |\n",
        "            |\n",
        "            |\n",
        "            |\n",
        "    =========\n",
        "    ''',\n",
        "    '''\n",
        "        -----\n",
        "        |   |\n",
        "        O   |\n",
        "            |\n",
        "            |\n",
        "            |\n",
        "    =========\n",
        "    ''',\n",
        "    '''\n",
        "        -----\n",
        "        |   |\n",
        "        O   |\n",
        "        |   |\n",
        "            |\n",
        "            |\n",
        "    =========\n",
        "    ''',\n",
        "    '''\n",
        "        -----\n",
        "        |   |\n",
        "        O   |\n",
        "       /|   |\n",
        "            |\n",
        "            |\n",
        "    =========\n",
        "    ''',\n",
        "    '''\n",
        "        -----\n",
        "        |   |\n",
        "        O   |\n",
        "       /|\\\\  |\n",
        "            |\n",
        "            |\n",
        "    =========\n",
        "    ''',\n",
        "    '''\n",
        "        -----\n",
        "        |   |\n",
        "        O   |\n",
        "       /|\\\\  |\n",
        "       /    |\n",
        "            |\n",
        "    =========\n",
        "    ''',\n",
        "    '''\n",
        "        -----\n",
        "        |   |\n",
        "        O   |\n",
        "       /|\\\\  |\n",
        "       / \\\\  |\n",
        "    =========\n",
        "    '''\n",
        "    ]\n",
        "    return stages[6 - attempts]  # Show the appropriate stage based on remaining attempts"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 18,
      "metadata": {
        "id": "GfVT6uIZUgGy"
      },
      "outputs": [],
      "source": [
        "def play_hangman(fname: str) -> None:\n",
        "    \"\"\"\n",
        "    Starts a game of Hangman using a word randomly chosen from a file.\n",
        "    - The game selects a word for the player to guess, letter by letter.\n",
        "    - The player has a limited number of incorrect guesses (6). After each guess, the game updates the displayed progress and the hangman figure.\n",
        "\n",
        "        Gameplay:\n",
        "        - The player inputs one letter per turn.\n",
        "        - Correct guesses reveal matching letters in the word.\n",
        "        - Incorrect guesses reduce the number of remaining attempts.\n",
        "        - The game ends when the word is guessed correctly or the player\n",
        "          runs out of attempts.\n",
        "\n",
        "    Args:\n",
        "        fname (str):            The path to the file containing a list of possible words.\n",
        "                                Each word should be on a separate line.\n",
        "\n",
        "    Returns:\n",
        "        None\n",
        "\n",
        "    Examples:\n",
        "    >>> Beginning\n",
        "\n",
        "        Welcome to Hangman!\n",
        "\n",
        "            -----\n",
        "            |   |\n",
        "                |\n",
        "                |\n",
        "                |\n",
        "                |\n",
        "            =========\n",
        "        _ _ _ _ _ _ _ _ _\n",
        "        Attempts remaining: 6\n",
        "        Guessed letters:\n",
        "        Enter a letter:\n",
        "\n",
        "    >>> Mid-game\n",
        "            -----\n",
        "            |   |\n",
        "            O   |\n",
        "                |\n",
        "                |\n",
        "                |\n",
        "            =========\n",
        "\n",
        "        _ _ _ _ _ _ _ _ y\n",
        "        Attempts remaining: 5\n",
        "        Guessed letters: y, z\n",
        "        Enter a letter: e\n",
        "        Sorry, 'e' is not in the word.\n",
        "\n",
        "    >>> End of game\n",
        "             -----\n",
        "             |   |\n",
        "             O   |\n",
        "            /|\\  |\n",
        "            / \\  |\n",
        "            =========\n",
        "\n",
        "        Game Over! The word was: authority\n",
        "    \"\"\"\n",
        "\n",
        "    print(\"Welcome to Hangman!\")\n",
        "    word_to_guess = choose_word(fname).lower()\n",
        "    guessed_letters = set()\n",
        "    attempts = 6\n",
        "    guessed_word_complete = False\n",
        "\n",
        "    while attempts > 0 and not guessed_word_complete:\n",
        "        print(display_hangman(attempts))\n",
        "        print(f\" {display_word(word_to_guess, guessed_letters)}\")\n",
        "        print(f\"\\nAttempts remaining: {attempts}\")\n",
        "        print(f\"Guessed letters: {', '.join(sorted(guessed_letters))}\")\n",
        "\n",
        "        guess = input(\"Enter a letter: \").lower()\n",
        "\n",
        "        if len(guess) != 1 or not guess.isalpha():\n",
        "            print(\"Invalid input. Please enter a single letter.\")\n",
        "        elif guess in guessed_letters:\n",
        "            print(\"You already guessed that letter.\")\n",
        "        else:\n",
        "            guessed_letters.add(guess)\n",
        "            if guess in word_to_guess:\n",
        "                print(f\"\\nGood guess! '{guess}' is in the word.\")\n",
        "                if all(letter in guessed_letters for letter in word_to_guess):\n",
        "                    guessed_word_complete = True\n",
        "            else:\n",
        "                print(f\"\\nSorry, '{guess}' is not in the word.\")\n",
        "                attempts -= 1\n",
        "\n",
        "    if guessed_word_complete:\n",
        "        print(\"\\nCongratulations! You guessed the word:\", word_to_guess)\n",
        "    else:\n",
        "        print(display_hangman(attempts))\n",
        "        print(\"\\nGame Over! The word was:\", word_to_guess)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 19,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "zkiYwJ8cUgIx",
        "outputId": "57f2a87b-2858-4f9e-c769-5b4b0aa991b3"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Welcome to Hangman!\n",
            "\n",
            "        -----\n",
            "        |   |\n",
            "            |\n",
            "            |\n",
            "            |\n",
            "            |\n",
            "    =========\n",
            "    \n",
            " _ _ _ _\n",
            "\n",
            "Attempts remaining: 6\n",
            "Guessed letters: \n",
            "Enter a letter: e\n",
            "\n",
            "Sorry, 'e' is not in the word.\n",
            "\n",
            "        -----\n",
            "        |   |\n",
            "        O   |\n",
            "            |\n",
            "            |\n",
            "            |\n",
            "    =========\n",
            "    \n",
            " _ _ _ _\n",
            "\n",
            "Attempts remaining: 5\n",
            "Guessed letters: e\n",
            "Enter a letter: s\n",
            "\n",
            "Sorry, 's' is not in the word.\n",
            "\n",
            "        -----\n",
            "        |   |\n",
            "        O   |\n",
            "        |   |\n",
            "            |\n",
            "            |\n",
            "    =========\n",
            "    \n",
            " _ _ _ _\n",
            "\n",
            "Attempts remaining: 4\n",
            "Guessed letters: e, s\n",
            "Enter a letter: t\n",
            "\n",
            "Sorry, 't' is not in the word.\n",
            "\n",
            "        -----\n",
            "        |   |\n",
            "        O   |\n",
            "       /|   |\n",
            "            |\n",
            "            |\n",
            "    =========\n",
            "    \n",
            " _ _ _ _\n",
            "\n",
            "Attempts remaining: 3\n",
            "Guessed letters: e, s, t\n",
            "Enter a letter: a\n",
            "\n",
            "Sorry, 'a' is not in the word.\n",
            "\n",
            "        -----\n",
            "        |   |\n",
            "        O   |\n",
            "       /|\\  |\n",
            "            |\n",
            "            |\n",
            "    =========\n",
            "    \n",
            " _ _ _ _\n",
            "\n",
            "Attempts remaining: 2\n",
            "Guessed letters: a, e, s, t\n",
            "Enter a letter: o\n",
            "\n",
            "Good guess! 'o' is in the word.\n",
            "\n",
            "        -----\n",
            "        |   |\n",
            "        O   |\n",
            "       /|\\  |\n",
            "            |\n",
            "            |\n",
            "    =========\n",
            "    \n",
            " _ o _ _\n",
            "\n",
            "Attempts remaining: 2\n",
            "Guessed letters: a, e, o, s, t\n",
            "Enter a letter: l\n",
            "\n",
            "Good guess! 'l' is in the word.\n",
            "\n",
            "        -----\n",
            "        |   |\n",
            "        O   |\n",
            "       /|\\  |\n",
            "            |\n",
            "            |\n",
            "    =========\n",
            "    \n",
            " _ o _ l\n",
            "\n",
            "Attempts remaining: 2\n",
            "Guessed letters: a, e, l, o, s, t\n",
            "Enter a letter: b\n",
            "\n",
            "Sorry, 'b' is not in the word.\n",
            "\n",
            "        -----\n",
            "        |   |\n",
            "        O   |\n",
            "       /|\\  |\n",
            "       /    |\n",
            "            |\n",
            "    =========\n",
            "    \n",
            " _ o _ l\n",
            "\n",
            "Attempts remaining: 1\n",
            "Guessed letters: a, b, e, l, o, s, t\n",
            "Enter a letter: p\n",
            "\n",
            "Sorry, 'p' is not in the word.\n",
            "\n",
            "        -----\n",
            "        |   |\n",
            "        O   |\n",
            "       /|\\  |\n",
            "       / \\  |\n",
            "    =========\n",
            "    \n",
            "\n",
            "Game Over! The word was: fowl\n"
          ]
        }
      ],
      "source": [
        "play_hangman('word_bank.txt')"
      ]
    }
  ],
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}
